### PR TITLE
Tested new languages as russian

### PR DESCRIPTION
**Pull request by carlosmn1997**
If I do a pull request with this change, will I do another pull request in order to earn the gift?

### CODE REVIEW

**Comment by fjlopez** [comment]
Check why Travis-CI can't access to your secrets.

**Comment by carlosmn1997** [comment]
The test branch is passing, the master one's no because I haven't do anything on it

**Comment by fjlopez** [comment]
Regarding to your question, that's the point. First pass with something extra simple (that pass the issue of the secrets), and then propose me what to do. I will guide you.

**Comment by carlosmn1997** [comment]
But, with my credentials in my test branch is going well, the problem is the branch in master should go with your credentials, am I right?

**Comment by fjlopez** [comment]
Don't worry, I've identified the issue https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions - my env variables are erased during the pull requests for security reasons.

**Pull request merged**
